// Sindiran pemerintahan & protes (aliran komedi/sarkas), dibalut dunia dungeon
// agar hidup & lucu tanpa menyasar pihak nyata. Setidaknya 25.
export const MEMES = [
  "Harga platinum naik dari 12 gold jadi 18 gold? Gold inflasi? Orang dungeon kan gak pakai platinum!",
  "Dihina-hina saya diam, dicaci maki saya masih diam, tapi di DungeonUnion ini saya katakan: SAYA AKAN LAWAN!",
  "Ngebuntal ni orang.",
  "Yang bikin minion kelaparan siapa? Bukan HQ. Pasti hero.",
  "Saya minta manajer bicara pakai hati, bukan pakai angka morale.",
  "Gaji ke-13? Di dungeon gaji ke-1 aja sering telat.",
  "Amanlah, aman. Trap sudah diatur. Yang kejebak cuma hero.",
  "Tidak ada niat jahat. Kami cuma lupa bayar gaji 3 bulan.",
  "Subsidi bawang dicabut demi stabilisasi… stabilisasi brankas HQ.",
  "Rakyat dungeon butuh bukan janji, tapi gold. Eh, dua-duanya nggak ada.",
  "Saya dipilih oleh minion untuk memimpin. Mereka terpaksa.",
  "BLT = Bantuan Langsung Trap. Gratis, tapi nyawamu yang bayar.",
  "Impor minion? Gak usah, kami ekspor trauma.",
  "Pajak dungeon naik, tapi lorong tetap gelap. Minimal gelapnya merata.",
  "Menteri Pertahanan tidur saat hero menyerang. Katanya lagi 'standby mode'.",
  "Ampun bang jago, jangan dipotong gajinya lagi.",
  "Tuhan baru aja kasih aku kesempatan jadi bos. Besoknya kena audit.",
  "Omong kosong? Itu KPI departemen HQ.",
  "Yang penting viral, bukan beres. Reputasi naik, morale turun.",
  "Demo minion dibubarkan alasan 'lorong lagi diperbaiki'.",
  "Infrastruktur dungeon 0%? Tenang, proposalnya 100%.",
  "Presiden dungeon: 'Saya merasakan yang kalian rasakan.' Padahal dia di menara bawang.",
  "Dana desa hilang? Mungkin jadi pupuk bawang.",
  "Lockdown lorong utara demi kesehatan. Brankas HQ tetap buka.",
  "Reformasi birokrasi: dari lambat jadi sangat lambat, tapi senyum.",
  "Copot menteri? Di dungeon kami copot gaji minion.",
  "Stabilitas 100% tercapai saat semua minion diam (dan trauma).",
  "Realisasi APBD dungeon 12%. Sisanya buat 'pengamanan brankas'.",
  "Vaksin hero? Yang bayar aja yang dapat. Yang gratis kena trap.",
  "Saya bukan anti-kritik, saya anti-minion yang ingat gajinya."
];
